/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EdgeAiRouteImport } from './routes/edge-ai'
import { Route as FleetRouteImport } from './routes/fleet'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EdgeAiRoute = EdgeAiRouteImport.update({
  id: '/edge-ai',
  path: '/edge-ai',
  getParentRoute: () => rootRouteImport,
} as any)
const FleetRoute = FleetRouteImport.update({
  id: '/fleet',
  path: '/fleet',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/edge-ai': typeof EdgeAiRoute
  '/fleet': typeof FleetRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/edge-ai': typeof EdgeAiRoute
  '/fleet': typeof FleetRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/edge-ai': typeof EdgeAiRoute
  '/fleet': typeof FleetRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/edge-ai' | '/fleet'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/edge-ai' | '/fleet'
  id: '__root__' | '/' | '/edge-ai' | '/fleet'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EdgeAiRoute: typeof EdgeAiRoute
  FleetRoute: typeof FleetRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/edge-ai': {
      id: '/edge-ai'
      path: '/edge-ai'
      fullPath: '/edge-ai'
      preLoaderRoute: typeof EdgeAiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fleet': {
      id: '/fleet'
      path: '/fleet'
      fullPath: '/fleet'
      preLoaderRoute: typeof FleetRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EdgeAiRoute: EdgeAiRoute,
  FleetRoute: FleetRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
